version = 0.1

[default.deploy.parameters]
stack_name = "xpenses-backend-prod"
resolve_s3 = true
s3_prefix = "xpenses-backend-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"prod\""
image_repositories = []
disable_rollback = true
