# app.py
"""PUT /transactions

Updates an existing transaction (full replace). Protected by the Cognito
Lambda Authorizer — `email` comes from the verified token
(requestContext.authorizer.email), not the body, so a caller can only ever
edit their own transactions. The body must include `transactionId` plus
every field (existing values included) since this replaces the item rather
than patching individual attributes.

Changing `date` is supported: the date is part of the item's key
(sk = "<date>#<transactionId>"), so when nothing exists under the body's
date, the transaction is found by its transactionId instead and moved: the
old item is deleted and the new one created in the same atomic write.

Account balances (see account.py) move from the old version's effect to the
new one atomically with the write.

Card statements (generated by the statements job) keep their identity: the
body can change amount, pending, accountId (the account that paid it),
title, categories and affectsBalance, but `type`, `targetAccountId` (the
card) and the `statement` breakdown always come from the stored item. Those
drive the next statement's carry-over. For any other transaction, a
`statement` in the body is ignored. Afterwards, the pending statement of any
credit card the old or new version touches is recalculated (so e.g. moving
a purchase off a card updates that card's statement too). A recalculated
pending statement keeps its title/categories/accountId, but its amount is
always the computed one.
"""
import json
import traceback
from datetime import date

import msgspec

from account import AccountNotFound, TransactionConflict, query_all_by_email, replace_transaction, swap_transactions
from http_utils import get_authenticated_email, json_response
from statement import parse_statement_item, sync_cards_touched_by
from transaction import build_sk, get_transactions_table, parse_transaction, transaction_to_item


def lambda_handler(event, context):
    # Catch-all so an unexpected crash still returns CORS headers instead of
    # a raw Lambda error the browser reports as an opaque "Failed to fetch".
    try:
        return _handle(event)
    except Exception:
        traceback.print_exc()
        return json_response(500, {"message": "Internal server error"})


def _handle(event):
    try:
        body = json.loads(event.get("body") or "{}")
    except json.JSONDecodeError as exc:
        return json_response(400, {"message": f"Invalid JSON: {exc}"})

    if "transactionId" not in body:
        return json_response(
            400, {"message": "transactionId is required to identify the transaction to edit"}
        )

    body["email"] = get_authenticated_email(event)
    # Server-derived: the key always comes from date + transactionId, never a client-sent sk
    body.pop("sk", None)
    body.pop("statement", None)

    try:
        sk = build_sk(date.fromisoformat(body["date"]), str(body["transactionId"]))
    except (KeyError, TypeError, ValueError):
        return json_response(400, {"message": "Invalid transaction: date must be a YYYY-MM-DD string"})

    table = get_transactions_table()
    existing = table.get_item(Key={"email": body["email"], "sk": sk}).get("Item")
    if not existing:
        # Not under the body's date: either it doesn't exist, or the date is being changed
        matches = [
            item
            for item in query_all_by_email(table, body["email"])
            if item.get("transactionId") == str(body["transactionId"])
        ]
        if not matches:
            return json_response(404, {"message": "Transaction not found"})
        if len(matches) > 1:
            # Only possible with client-chosen transactionIds reused on different dates
            return json_response(
                409, {"message": "transactionId exists on more than one date; edit it without changing the date"}
            )
        existing = matches[0]

    if existing.get("statement"):
        if existing["date"] != body["date"]:
            return json_response(
                400, {"message": "A card statement's date is the card's due date and can't be changed"}
            )
        # Applied before validating, so a body with stale/edited values for these still works
        body["type"] = existing["type"]
        body["targetAccountId"] = existing["targetAccountId"]

    try:
        transaction = parse_transaction(body)
    except msgspec.ValidationError as exc:
        return json_response(400, {"message": f"Invalid transaction: {exc}"})
    if existing.get("statement"):
        transaction.statement = parse_statement_item(existing["statement"])

    try:
        if transaction.sk == existing["sk"]:
            replace_transaction(existing, transaction)
        else:
            # Date changed -> new key: delete + insert atomically (fails if the new key is taken)
            swap_transactions([existing], [transaction])
    except TransactionConflict:
        return json_response(
            409, {"message": "Transaction was changed or deleted by another request; reload it and retry"}
        )
    except AccountNotFound as exc:
        return json_response(400, {"message": str(exc)})

    sync_cards_touched_by(transaction.email, [existing, transaction_to_item(transaction)])
    return json_response(200, msgspec.to_builtins(transaction))


if __name__ == "__main__":
    from datetime import date

    try:
        from dotenv import load_dotenv

        load_dotenv()
    except ImportError:
        pass

    from transaction import TransactionType, put_transaction

    TEST_EMAIL = "jane@test"

    # Seed a transaction directly so there's something to edit
    table = get_transactions_table()
    seed = parse_transaction(
        {
            "email": TEST_EMAIL,
            "title": "Seed for edit test",
            "amount": "5.00",
            "categories": ["testing"],
            "date": date.today().isoformat(),
            "type": TransactionType.EXPENSE.value,
            "affectsBalance": True,
            "pending": False,
        }
    )
    put_transaction(table, seed)

    body = json.dumps(
        {
            "email": TEST_EMAIL,  # overwritten by the (simulated) authorizer context below anyway
            "title": "Edited via local test",
            "amount": "7.25",
            "categories": ["testing", "edited"],
            "date": seed.date.isoformat(),
            "type": TransactionType.EXPENSE.value,
            "affectsBalance": True,
            "pending": False,
            "transactionId": seed.transactionId,
        }
    )
    event = {"body": body, "requestContext": {"authorizer": {"email": TEST_EMAIL}}}
    result = lambda_handler(event, None)
    print(result)
